version: '2'
services:
  app:
    build:
      context: app
      args:
        uid: ${UID}
    container_name: pie-store-app
    restart: ${RESTART_POLICIES}
    depends_on:
      - db
      - redis
    volumes:
      - "../app:/var/www/html"
    env_file: .env
  nginx:
    build: ./nginx
    container_name: pie-store-nginx
    restart: ${RESTART_POLICIES}
    depends_on:
      - app
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - "../app:/var/www/html/"
      - "./nginx/conf.d:/etc/nginx/conf.d/"
    env_file: .env
  db:
    build: db
    container_name: pie-store-db
    restart: ${RESTART_POLICIES}
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    volumes:
      - "${DB_EXTERNAL_DATA}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
  redis:
    build: redis
    container_name: pie-store-redis
    restart: ${RESTART_POLICIES}